kind: Service
apiVersion: v1
metadata:
  name: xdrienovskym2-ambulance-ufe   
spec:
  selector:
    pod: xdrienovskym2-ambulance-ufe-label    
  ports:
  - name: http
    protocol: TCP
    port: 80          
                        
    targetPort: http    