apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: xdrienovskym2-ambulance-ufe-content
spec:
  microFrontend: xdrienovskym2-ambulance-ufe
  element: xdrienovskym2-ambulance-wl-app
  attributes:
    - name: api-base
      value: /api
    - name: ambulance-id
      value: bobulova
    - name: base-path
      value: /xdrienovskym2-ambulance-wl/
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?xdrienovskym2-ambulance-wl(/.*)?$"
