apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
images:
- name: matejdrienovsky/ambulance-ufe
  newName: matejdrienovsky/ambulance-ufe # {"$imagepolicy": "wac-hospital:ambulance-ufe:name"}
  newTag: main.20260317.1355 # {"$imagepolicy": "wac-hospital:ambulance-ufe:tag"}
- name: <docker-id>/ambulance-wl-webapi
  newName: matejdrienovsky/ambulance-wl-webapi # {"$imagepolicy": "wac-hospital:ambulance-webapi:name"}
  newTag: main # {"$imagepolicy": "wac-hospital:ambulance-webapi:tag"}
