apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wac-hospital

labels:
- pairs:
    app.kubernetes.io/part-of: wac-hospital
    app.kubernetes.io/name: xdrienovskym2-ambulance-wl
    wac-fiit.github.io/project: xdrienovskym2-ambulance-wl
  includeSelectors: true
  includeTemplates: true

resources:
- ../../../apps/xdrienovskym2-ambulance-ufe
- ../../../apps/xdrienovskym2-ambulance-webapi

components:
- ../../../components/version-release
