apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- pairs:
    app.kubernetes.io/name: xdrienovskym2-apps
    app.kubernetes.io/instance: release
    app.kubernetes.io/version: "1.0.0"
    wac-fiit.github.io/project: xdrienovskym2-ambulance-wl

resources:
- gitops
